name: Continuous Integration
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  FLEET_SERVER_VERSION: 7.13.1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - 
        name: Build fleet-server for arm64
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v2
        with:
          push: false
          platforms: linux/arm64
          tags: fgierlinger/fleet-server:${{ env.FLEET_SERVER_VERSION }}
          file: Dockerfile
          build-args: FLEET_SERVER_VERSION=${{ env.FLEET_SERVER_VERSION }}
      - 
        name: Build fleet-server for arm64
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm64
          tags: fgierlinger/fleet-server:${{ env.FLEET_SERVER_VERSION }}
          file: Dockerfile
          build-args: FLEET_SERVER_VERSION=${{ env.FLEET_SERVER_VERSION }}